/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Insurance;
import java.awt.CardLayout;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @angela
 */
public class InsuranceFrame extends javax.swing.JFrame {
    private Vector _assurances = new Vector();
    private Assurance _insurance;
    
    public InsuranceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupInsurance = new javax.swing.ButtonGroup();
        jPanelNorth = new javax.swing.JPanel();
        jRadioButtonHousing = new javax.swing.JRadioButton();
        jRadioButtonMedicate = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPolicy = new javax.swing.JTextField();
        jTextFieldCommision = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jPanelCenter = new javax.swing.JPanel();
        jPanelHousing = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jTextFieldValueLand = new javax.swing.JTextField();
        jTextFieldPercentage = new javax.swing.JTextField();
        jPanelMedicate = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAge = new javax.swing.JTextField();
        jComboBoxPremium = new javax.swing.JComboBox<>();
        jPanelSouth = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonSummary = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insurance Application");

        buttonGroupInsurance.add(jRadioButtonHousing);
        jRadioButtonHousing.setSelected(true);
        jRadioButtonHousing.setText("Housing");
        jRadioButtonHousing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHousingActionPerformed(evt);
            }
        });

        buttonGroupInsurance.add(jRadioButtonMedicate);
        jRadioButtonMedicate.setText("Medicate");
        jRadioButtonMedicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMedicateActionPerformed(evt);
            }
        });

        jLabel1.setText("Policy");

        jLabel2.setText("Name");

        jLabel3.setText("Commision");

        jTextFieldCommision.setText("0.15");

        javax.swing.GroupLayout jPanelNorthLayout = new javax.swing.GroupLayout(jPanelNorth);
        jPanelNorth.setLayout(jPanelNorthLayout);
        jPanelNorthLayout.setHorizontalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelNorthLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelNorthLayout.createSequentialGroup()
                        .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelNorthLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jTextFieldPolicy))
                            .addComponent(jRadioButtonHousing, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNorthLayout.createSequentialGroup()
                                .addComponent(jRadioButtonMedicate, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNorthLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCommision, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanelNorthLayout.setVerticalGroup(
            jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNorthLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHousing)
                    .addComponent(jRadioButtonMedicate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCommision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanelNorth, java.awt.BorderLayout.NORTH);

        jPanelCenter.setLayout(new java.awt.CardLayout());

        jLabel6.setText("Location");

        jLabel7.setText("Value of Land");

        jLabel8.setText("Porcentage");

        javax.swing.GroupLayout jPanelHousingLayout = new javax.swing.GroupLayout(jPanelHousing);
        jPanelHousing.setLayout(jPanelHousingLayout);
        jPanelHousingLayout.setHorizontalGroup(
            jPanelHousingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHousingLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelHousingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jPanelHousingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelHousingLayout.createSequentialGroup()
                        .addComponent(jTextFieldValueLand, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldLocation))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelHousingLayout.setVerticalGroup(
            jPanelHousingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHousingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelHousingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanelHousingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldValueLand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanelCenter.add(jPanelHousing, "Housing");

        jLabel4.setText("Age");

        jLabel5.setText("Premium");

        jComboBoxPremium.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20", "40", "60", "80", "100" }));

        javax.swing.GroupLayout jPanelMedicateLayout = new javax.swing.GroupLayout(jPanelMedicate);
        jPanelMedicate.setLayout(jPanelMedicateLayout);
        jPanelMedicateLayout.setHorizontalGroup(
            jPanelMedicateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMedicateLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addGap(54, 54, 54)
                .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanelMedicateLayout.setVerticalGroup(
            jPanelMedicateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMedicateLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelMedicateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMedicateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanelCenter.add(jPanelMedicate, "Medicate");

        getContentPane().add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSummary.setText("Summary");
        jButtonSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSummaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSouthLayout = new javax.swing.GroupLayout(jPanelSouth);
        jPanelSouth.setLayout(jPanelSouthLayout);
        jPanelSouthLayout.setHorizontalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addGap(92, 92, 92)
                .addComponent(jButtonSummary)
                .addGap(112, 112, 112))
        );
        jPanelSouthLayout.setVerticalGroup(
            jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSouthLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelSouthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonSummary))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonHousingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHousingActionPerformed
        ((CardLayout)jPanelCenter.getLayout()).show(jPanelCenter,"Housing");
    }//GEN-LAST:event_jRadioButtonHousingActionPerformed

    private void jRadioButtonMedicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMedicateActionPerformed
        ((CardLayout)jPanelCenter.getLayout()).show(jPanelCenter,"Medicate");
    }//GEN-LAST:event_jRadioButtonMedicateActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        int policy = Integer.parseInt( jTextFieldPolicy.getText() );
        String name = jTextFieldName.getText();
        float commission = Float.parseFloat( jTextFieldCommision.getText() );
        
        if( jRadioButtonHousing.isSelected() ){
            String location = jTextFieldLocation.getText();
            double valueLand = Double.parseDouble( jTextFieldValueLand.getText() );
            float percentage = Float.parseFloat( jTextFieldPercentage.getText() );
            _insurance = new AssuranceHousing(policy, name, commission, location, valueLand, percentage );
        }
        else{
            float premium = Float.parseFloat(jComboBoxPremium.getSelectedItem().toString() );
            int age = Integer.parseInt( jTextFieldAge.getText() );
            _insurance = new AssuranceMedicate(policy, name, commission, premium, age);
        }
        
        _insurance.calculatePremium();
        _insurance.calculateCoverage();
        _assurances.addElement( _insurance );
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSummaryActionPerformed
        double summary = 0, sumValueLand = 0, averageValueland = 0;
        int sumAge = 0, countMedicate = 0, countHousing = 0, averageAge = 0;
        
        for(Object insurance : _assurances ) {
            summary = summary + ((Assurance)insurance).getCoverage();
            
            if( insurance instanceof AssuranceMedicate ){
                countMedicate++;
                sumAge = sumAge + ((AssuranceMedicate)insurance).getAge();
            }
            if( insurance instanceof AssuranceHousing){
                countHousing++;
                sumValueLand = sumValueLand +((AssuranceHousing)insurance).getValueLand();
            }
        }
        
        if (countMedicate != 0)
            averageAge = sumAge/countMedicate;
        if( countHousing != 0)
            averageValueland = sumValueLand / countHousing;
        
        JOptionPane.showMessageDialog(this,
            "La cobertura del total de seguros es: "+ summary +
            "\nLos seguros médicos tienen una edad promedio: " + averageAge +
            "\nLos seguros de vivienda tienen valor de la vivienda promedio: "+ averageValueland, 
            "Insurance Application",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonSummaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsuranceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupInsurance;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonSummary;
    private javax.swing.JComboBox<String> jComboBoxPremium;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelHousing;
    private javax.swing.JPanel jPanelMedicate;
    private javax.swing.JPanel jPanelNorth;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JRadioButton jRadioButtonHousing;
    private javax.swing.JRadioButton jRadioButtonMedicate;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldCommision;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPercentage;
    private javax.swing.JTextField jTextFieldPolicy;
    private javax.swing.JTextField jTextFieldValueLand;
    // End of variables declaration//GEN-END:variables
}
